module.exports = {

  neverHaveIEver: [
    "Never have I ever texted someone and immediately regretted it",
    "Never have I ever woken up not knowing where I was",
    "Never have I ever kissed someone whose name I didn't know",
    "Never have I ever lied about being sick to skip work or school",
    "Never have I ever gone skinny dipping",
    "Never have I ever done something embarrassing on a first date",
    "Never have I ever drunk-dialed an ex",
    "Never have I ever made out with someone at a party within 20 mins of meeting them",
    "Never have I ever sent a risky photo to the wrong person",
    "Never have I ever pretended to be drunker than I was",
    "Never have I ever hooked up with someone and immediately wanted to leave",
    "Never have I ever passed out at a party and woken up in a weird place",
    "Never have I ever done a walk of shame",
    "Never have I ever gotten into a fight over something embarrassingly stupid",
    "Never have I ever stolen something from a bar",
    "Never have I ever lied to get out of a date",
    "Never have I ever cried in the shower",
    "Never have I ever snuck someone into my place without my roommates knowing",
    "Never have I ever used someone else's Netflix without asking",
    "Never have I ever gone on vacation just to avoid someone",
    "Never have I ever faked enthusiasm about a gift",
    "Never have I ever drunkenly ordered food and forgotten about it until it arrived",
    "Never have I ever blocked someone and then unblocked them just to check their profile",
    "Never have I ever matched with someone on a dating app and immediately panicked",
    "Never have I ever kept chatting with someone just for the attention"
  ],

  wouldYouRather: [
    { a: "Be caught singing in the shower", b: "Be caught reading someone's texts" },
    { a: "Text your ex right now", b: "Let everyone read your last 10 texts" },
    { a: "Have no filter for one day", b: "Be invisible for one day" },
    { a: "Date someone 15 years older", b: "Date someone 15 years younger" },
    { a: "Never drink again", b: "Never have sex again" },
    { a: "Find out your best friend has been lying to you", b: "Find out your partner has been lying to you" },
    { a: "Always say what you're thinking", b: "Never be able to speak again" },
    { a: "Have everyone know your browser history", b: "Have everyone know your bank account balance" },
    { a: "Kiss your worst enemy", b: "Never kiss anyone you like again" },
    { a: "Go to jail for a week", b: "Lose all your friends" },
    { a: "Be famous but hated", b: "Be unknown but loved" },
    { a: "Have your ex read your diary", b: "Have your parents read your texts" },
    { a: "Know when you're going to die", b: "Know how everyone around you feels about you" },
    { a: "Have one wild night you can never remember", b: "Have one boring night you can never forget" },
    { a: "Tell your most embarrassing story to your coworkers", b: "Let your coworkers see your camera roll" },
  ],

  mostLikelyTo: [
    "Most likely to cry at a movie they've seen 10 times",
    "Most likely to drunk text their ex tonight",
    "Most likely to end up on a reality TV show",
    "Most likely to get kicked out of a bar",
    "Most likely to start a cult",
    "Most likely to marry someone they met on a flight",
    "Most likely to fake their own death to avoid responsibilities",
    "Most likely to wake up in another country with no plan",
    "Most likely to argue with a stranger on the internet for 3 hours",
    "Most likely to ghost someone after a great date",
    "Most likely to quit their job on a whim",
    "Most likely to date someone their friends hate",
    "Most likely to be the one who 'just needs 5 more minutes'",
    "Most likely to accidentally spill a secret",
    "Most likely to fall asleep first tonight",
    "Most likely to cause a scene at a restaurant",
    "Most likely to still be awake at 5am",
    "Most likely to kiss someone in this room tonight",
  ],

  trivia: [
    { q: "What country drinks the most alcohol per capita?", a: "Czech Republic", options: ["Russia", "Czech Republic", "Germany", "Ireland"] },
    { q: "How many standard drinks does it take to reach 0.08 BAC for an average person?", a: "4", options: ["2", "3", "4", "6"] },
    { q: "What is the main ingredient in tequila?", a: "Blue agave", options: ["Cactus", "Blue agave", "Sugar cane", "Corn"] },
    { q: "Which country invented champagne?", a: "France", options: ["Italy", "Spain", "France", "England"] },
    { q: "What does 'Beer before liquor' supposedly do?", a: "Make you sicker", options: ["Make you drunker", "Make you sicker", "Make you tired", "Nothing"] },
    { q: "What year was the legal drinking age raised to 21 in the US?", a: "1984", options: ["1976", "1980", "1984", "1990"] },
    { q: "What cocktail is made with vodka, lime juice, and ginger beer?", a: "Moscow Mule", options: ["Dark & Stormy", "Moscow Mule", "Buck's Fizz", "Gimlet"] },
    { q: "What does 'proof' mean on a bottle of alcohol?", a: "Double the ABV%", options: ["The ABV%", "Double the ABV%", "Quality rating", "Origin certificate"] },
    { q: "Which beer brand uses a red triangle as its logo?", a: "Bass", options: ["Budweiser", "Heineken", "Bass", "Stella Artois"] },
    { q: "What is the alcohol content of standard wine?", a: "12-15%", options: ["5-8%", "9-11%", "12-15%", "18-22%"] },
    { q: "What is sake made from?", a: "Rice", options: ["Barley", "Rice", "Wheat", "Potatoes"] },
    { q: "Which city is known as the craft beer capital of the US?", a: "Portland", options: ["Denver", "Portland", "San Diego", "Austin"] },
    { q: "What is the world's best-selling spirit?", a: "Baijiu", options: ["Vodka", "Whiskey", "Rum", "Baijiu"] },
    { q: "What gives red wine its red colour?", a: "Grape skins", options: ["Grape juice", "Grape skins", "Oak barrels", "Additives"] },
    { q: "What is a 'boilermaker'?", a: "Beer with a shot of whiskey", options: ["Beer with a shot of whiskey", "Double espresso shot", "Mixed cocktail", "Craft IPA"] },
  ],

  hotTakes: [
    "Pineapple on pizza is actually good",
    "Beer tastes better out of a can than a bottle",
    "Whiskey is overrated and people only pretend to like it",
    "Going out is overrated — staying in is always better",
    "Social media has made dating impossible",
    "Most people's political opinions are just their parents' opinions",
    "People who say they 'don't watch TV' are insufferable",
    "Brunch is a scam and breakfast is better",
    "Long distance relationships never work",
    "Gen Z is actually more responsible than millennials",
    "Tattoos make people more attractive",
    "People who don't drink are suspicious",
    "Morning people are just bragging",
    "Most people would cheat if they knew they'd never get caught",
    "Astrology is just therapy for people who won't go to therapy",
    "Snapchat streaks are a form of emotional manipulation",
    "Most friendships are just convenience",
    "Red flags are only red flags if you're not attracted to the person",
  ],

  rapidFire: [
    { prompt: "Name 5 cocktails in 10 seconds!", type: "timer", seconds: 10 },
    { prompt: "Say the alphabet backwards — GO!", type: "timer", seconds: 15 },
    { prompt: "Name 3 people in this room you'd trust with your life!", type: "social" },
    { prompt: "Do your best impression of someone in this room!", type: "social" },
    { prompt: "Name 10 countries in 15 seconds!", type: "timer", seconds: 15 },
    { prompt: "Say 'red lorry yellow lorry' 5 times fast!", type: "timer", seconds: 8 },
    { prompt: "Name every US president you know in 20 seconds!", type: "timer", seconds: 20 },
    { prompt: "Do 10 push-ups or take 2 sips!", type: "social" },
    { prompt: "Whisper something you've never told anyone to the person on your left!", type: "social" },
    { prompt: "Call someone NOT in this room and say 'I miss you' then hang up!", type: "social" },
    { prompt: "Text your most recent contact a random emoji with no explanation!", type: "social" },
    { prompt: "Name 5 capitals of countries in 10 seconds!", type: "timer", seconds: 10 },
    { prompt: "Everyone votes: who in this room would survive a zombie apocalypse?", type: "vote" },
    { prompt: "Post something to your story RIGHT NOW or drink!", type: "social" },
    { prompt: "Act out your most embarrassing moment — no words!", type: "social" },
  ]
};
